### ISSUE TITLE
Generate Unique ID For Each TODO

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#10]
Each found TODO should be assigned a unique id, a hash between body, originating ticket and estimation.
Two TODOs should have the same ID/hash only if they have identical body, originating ticket and estimation.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@lukacupic this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-22T16:40:32.187745``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@lukacupic Don't forget to close this ticket before the deadline (2020-11-22T16:40:32). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@lukacupic Thanks for fixing it, paid with transaction id: 03C31173WT9230419

PayPal tells me the transaction is "Pending" and that you have to accept it. It's the first time this happens, maybe it's some setting on your side, I'm not sure.

**Comment by lukacupic** [comment]
> @lukacupic Thanks for fixing it, paid with transaction id: 03C31173WT9230419
> 
> PayPal tells me the transaction is "Pending" and that you have to accept it. It's the first time this happens, maybe it's some setting on your side, I'm not sure.

Thank you! Yes, I forgot I had to verify my account. It's all good now. Thanks :)

**Comment by charlesmike** [comment]
@lukacupic thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
