### ISSUE TITLE
Estimation format should only accept minutes.

### ISSUE THREAD

**Issue by criske** [self-xdsd/todo-finder-cli#16]
Estimations should have minutes in the format of `m`,`min` or `mins` :

- `#100:30m`
- `#100:30min`
- `#100:30mins`

https://github.com/self-xdsd/todo-finder-cli/blob/5d4186685444cdbd3da4e884250f3543e88a458e/src/main/java/com/selfxdsd/todocli/TodoParser.java#L96

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-28T10:32:16.018127``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
