### ISSUE TITLE
Implement -v, --v, -version, --version

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#19]
These flags should all print out the version of the utilitary (it's usually the first thing users of a CLI utilitary try to call after installing it).

We should start with an elegant solution for parsing and handling command-line arguments, since we will have more options/flags later.

**Comment by charlesmike** [comment]
@lukacupic this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-29T12:31:25.045828``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@lukacupic thanks! Paid with transaction id 9KY76197W3769411C

**Comment by charlesmike** [comment]
@lukacupic thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
