### ISSUE TITLE
Looks very elegant!

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#2]
Hi @lukacupic 

I had a look now, looks very nice.
Can you please do the following changes?

1. Change the base package name and maven groupId to: ``com.selfxdsd``. Also, change the artifactId from ``TodoCLI`` to ``todo-finder-cli``. 

2. The tests look nice, but can you also add some assertions for the body of the todo? So far, I only notice assertions for the ticket and estimation :D 

3. Parameter Todo.estimatedTime should be an integer. Estimation should always be in minutes. No days or other things, just minutes. 

4. Can you please explain how will this be extended to work with other files than Java? I think the ``TodoParser`` should be parameterized somehow (based on the file extension maybe) and use slightly different regexes depending on the programming language, right?

**Comment by lukacupic** [comment]
Hi @amihaiemil 

I just fixed 1-3 and pushed everything to master.

Regarding parser's extension: Yes, something like sounds good. I was thinking about employing another kind of visitor pattern in which the main parser would delegate parsing to other language-specific parsers. E.g. a JavaTodoParser would parse a Java file, and a RubyTodoParser would parse a Ruby file.

Furhermore, we could find some common elements between all parsers and extract them into the main parser. The main parser would simply call an interface method of a language parser, which would extract and return the found Todo objects. The language-specific parser would ideally have as little logic as possible, with a focus only on the language comments and their regexes.

This is all from the top of my head, so I could be missing something. But all in all, it sounds quite feasible and interesting to implement!

**Comment by amihaiemil** [comment]
@lukacupic Thanks, but I see no change regarding point 2. Can you also add some assertions about the body of the todos?:D

**Comment by lukacupic** [comment]
@amihaiemil Here's the method: [whenParsingTodoWithBody_ExpectBodyToBeProperlyParsed](https://github.com/lukacupic/TodoCLI/blob/32d90110b990c53f777ca7a6bcc6207734735977/src/test/java/com/selfxdsd/todocli/TodoParserTest.java#L61)

**Comment by amihaiemil** [comment]
@lukacupic Right, I missed that. Thank you!
