### ISSUE TITLE
Update TODO Json

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#22]
At the moment the JSON todo output is:

```java
{
    "ticket": "#15",
    "estimate": 15,
    "body": "This a todo in a js file and has a multiline body.",
    "lines": "2-3",
    "file": "./target/test-classes/js/JsTodos.js"
}
```

Two changes are needed: rename ``ticket`` to ``originatingTicket`` and add the TODO's ID.

**Comment by charlesmike** [comment]
@lukacupic this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-04T11:33:39.015798``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 4GH90849578091813

**Comment by charlesmike** [comment]
@lukacupic thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
