### ISSUE TITLE
JsonTodosSerializer needs to use JsonTodo/JsonTodos on serialization.

### ISSUE THREAD

**Issue by criske** [self-xdsd/todo-finder-cli#23]
Right now is using the json lower level api when serializing todos. 

https://github.com/self-xdsd/todo-finder-cli/blob/9d2ad95ead36e6d63238a0d71a4c5a12270ffd01/src/main/java/com/selfxdsd/todocli/JsonTodosSerializer.java#L71

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-04T15:31:53.811955``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
