### ISSUE TITLE
Ignore TODOs with empty body or Autogenerated

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#34]
If the todo has an empty body or has a body which starts with "Autogenerated", they should be ignored. 

Usually the IDE Will create todos such as "todo Autogenerated method stub", which we should try to ignore.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-21T17:28:50.477296``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 0K180040UC7352842

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
