### ISSUE TITLE
Allow Any File to be Parsed

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#35]
I think we should remove that if statement (``if file JS or Java``) and allow the parsing of any file. 
This will cover the majority of programming languages and for others simply no todos will be found.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-21T17:32:12.695503``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
> This will cover the majority of programming languages and for others simply no todos will be found.

@amihaiemil I think it shouldn't be too hard to retrofit the parser to support other languages in the future. (for ex python which is pretty popular).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
