### ISSUE TITLE
Todo as JsonObject

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#4]
The output should be a JsonArray with Todos as JsonObject. For Json, we should use JSON-P:

```java
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.json</artifactId>
    <version>1.1.4</version>
</dependency>
```

We will need AbstractJsonObject and AbstractJsonArray in order to implement polymorphism. Have a look at these classes: https://github.com/self-xdsd/self-web/tree/master/src/main/java/com/selfxdsd/selfweb/api/output. It should be the same pattern.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@lukacupic this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-21T15:17:21.139403``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@lukacupic Don't forget to close this ticket before the deadline (2020-11-21T15:17:21). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@lukacupic Thanks, paid with transaction id 73Y16644SU798442P.

Same here, PayPal says the transaction is "Pending" and that you have to accept it.

**Comment by charlesmike** [comment]
@lukacupic thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
