### ISSUE TITLE
Use Only JsonPuzzles

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#41]
I liked the PuzzlesFallback mechanism initially, but it turns out it doesn't make sense:

- if we use a single pdd tool (todo-finder-cli or the original ``pdd``), then only one of the parsers will work (the fallback will never work)
- the fallback would have a chance to work only if we use both tools (todo-finder-cli and the original pdd). This is unfortunately not possible because the tools are generating different IDs for the same puzzle -- if we use them interchangibly, we will have duplicate Issues reported and so on.

In this ticket please make sure only JsonPuzzles is used. Do not remove XmlPuzzles and PuzzlesFallback, maybe we will use them again later.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-07T15:34:31.797936``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
@amihaiemil Right, I've missed the `id` part. It would've been nice to change the parsers on the fly in `cloneRepoAndPdd.sh`.
Is still possible though, if we adapt the `pdd`  id generator strategy to `todo-finder-cli` :D
 It looks like they using this format:
[`<originatingTicket>-<first_eight_characters_of_md5_body_hash>`](https://github.com/yegor256/pdd/blob/2836ea6d2edb72437bff639d84aef26743a94fb5/lib/pdd/source.rb#L107)

**Comment by amihaiemil** [comment]
@criske maybe, but pdd is also very error-prone, it fails if you have the word ``todo`` anywhere in your repository. 
For instance it crashes in the repo ``todo-finder-cli`` because of the project name... 

So I don't think we will be using it in prod anytime soon. If todo-finder-cli will fail, it's almost guaranteed that pdd will fail as well :D

**Comment by criske** [comment]
@amihaiemil Ok, I've opened a PR in [`self-todos`.](https://github.com/self-xdsd/self-todos/pull/41) I think this issue is safe to be closed.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
