### ISSUE TITLE
Generate todos.json In The Running Folder

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#42]
At the moment the file ``todos.json`` is always generated in the folder where the application resides (the folder where the ``todos-finder-cli.jar`` is residing).

Instead, it should be generated in the folder where the application is run (the folder which is scanned for todos).

Behaviour:

We are in folder ``/home/apps/self-web`` and we are running the command ``java -jar /home/jars/todo-finder-cli.jar``. The file ``todos.json`` is generated in the folder ``/home/jars``. Instead, it should be generated in ``/home/apps/self-web``.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-07T15:38:20.893048``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
