### ISSUE TITLE
Read TODO Author and Timestamp

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#46]
If the folder we're running in is a git repository, we should read the history and extract the author and timestamp when the todo has been written.

Here's somewhere to start from: https://stackoverflow.com/questions/50895244/how-to-get-git-log-of-all-branches-in-java

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-17T16:50:09.009954``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske have a look here when you have some time, treat this as a research task :D it's enough if you come up with possible solutions.

To be honest, I have no idea how to achieve this and following the pattern of self-todos (connecting via SSH etc) seems too complicated for this.

**Comment by criske** [comment]
@amihaiemil  A rough idea:

We need to change the Todo API to accept `author` and `timestamp` first.

Then for each file we get commit hashes in reverse order from oldest to latest.
`git log --reverse`

Now for each commit  we do a  `git show <hash>` then
extract the `author`, `timestamp` and parse commit body for todos.

The hardest part will be to check if a todo is changing across commits, is deleted or moved.
I guess we'll need to keep a  `Map<int, Todo>` across commits, where key is the todo start line.

For example 
In `todoList()` of commit "a123" we have a `Todo` that starts at line 10.
Then we will add this todo to map ->  `map[10] = Todo(..,"This is a todo")` 

In next commit "b123" 
we check in the generated `todoList()`  if there is a todo that starts at 10.
- If is then we update the map with this updated todo (this todo might have different body from the one of previous commit and thus has new timestamp).
- If isn't, just remove map[10] -> this means it was either removed or moved to an other line.


When we're done with all commits, we take the map values and save them to `todo.json` as usual. In theory we should have the latest todos with correct timestamps from all file commits.

**Comment by amihaiemil** [comment]
@criske yes, that's an algorithm of how to parse it. But how to actually access the git history from Java? :))

**Comment by criske** [comment]
@amihaiemil Run `git` with `Runtime` class. Or do you want do it without `git` being installed?

**Comment by amihaiemil** [comment]
@criske that could work. I never used the Runtime class before.

As an idea about the algorithm: I think we just need to run git blame and see who commited the lines of the todo and when.

We dont need to check for removed or last updated commits because we already have the latest info from git blame. And if the todo was removed, we won't even find it to begin with.

**Comment by criske** [comment]
@amihaiemil I forgot about git blame, this makes everything much easier. :D

**Comment by amihaiemil** [comment]
paid with transaction id 14A52889024706721

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
