### ISSUE TITLE
Output in file todos.json

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#5]
The output should be written to a file called ``todos.json``, to be created in the same folder where the utilitary is run.
If the todos.json file already exists from a previous run, it should be removed and a new one should be created.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-21T15:17:24.720125``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
paid with transaction id 8HD45367NV312910J

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
