### ISSUE TITLE
Add Proper Logging

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#6]
We should add proper logging using SLF4J and Log4J. The default console appender is ok. 
We should log each file being processed and the number of todos (And their lines) found in the respective file.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@lukacupic this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-21T15:17:28.335632``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@lukacupic Don't forget to close this ticket before the deadline (2020-11-21T15:17:28). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@lukacupic Thanks for solving it. Paid with transaction ID 79V75159MH135171P

**Comment by charlesmike** [comment]
@lukacupic thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
