### ISSUE TITLE
Allow ".js" files to be parsed for todos.

### ISSUE THREAD

**Issue by criske** [self-xdsd/todo-finder-cli#7]
https://github.com/self-xdsd/todo-finder-cli/blob/a44545092b6589f3e805fe4e4b434642f7a73466/src/main/java/com/selfxdsd/todocli/TodoVisitor.java#L74

Sometimes frontend of `self-xdsd/self-web` has [todos](https://github.com/self-xdsd/self-web/issues/170) in  js files.

**Comment by amihaiemil** [comment]
Actually, I think the implemented logic should already work for most programming languages. We are currently looking at single line comments ``//``,

Multi-line commments:

```java
/* 

*/
```
and JavaDocs
```java
/**
 *
 *
 */
```

Single line and multi-line comments are the same in Java, C, C++, C#, JS... these languages do not have javadocs, but the javadoc format is actually a valid multi-line comment in these languages.

So maybe we should just remove that ``if``...

**Comment by criske** [comment]
> So maybe we should just remove that `if`...

@amihaiemil yes, only that line.
Edit: I think is better to add `file.endsWith(".java") || file.endsWith(".js")` to avoid trying to parse any file?

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-21T15:17:31.590076``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
