### ISSUE TITLE
Write Author and Timestamp to JSON

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/todo-finder-cli#72]
I can see the author and timestamp in the logs, but it's not written to the todos.json file. Let's do that as well :D

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-18T11:08:19.364449``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
@amihaiemil sorry about that, I forgot to update JsonTodo. I'll fix asap.

**Comment by amihaiemil** [comment]
@criske np

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
