### ISSUE TITLE
TodosWithBodies.java: Single line todo method H. @t... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/todo-finder-cli#78]
The puzzle ``1398773404`` originating from #200 has to be resolved:

https://github.com/self-xdsd/todo-finder-cli/blob/7db5c71cb391e91937cd57e5254faadb0cce1086/src/test/resources/TodosWithBodies.java#L74-L75

"Single line todo method H. @todo #201:30min This a new todo an not part of the above todo.".

Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-03T15:26:27.486770``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
